WebMusic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('music/', include('music.urls')),
    path('category/', include('category.urls')),
    path('album/', include('album.urls')),
    path('artist/', include('artist.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

album/urls.py
from django.urls import path
from album import views

app_name = 'album'
urlpatterns = [
    path("",views.IndexView,name="index")
]

artist/urls.py
from django.urls import path

urlpatterns = [
]

category/urls.py
from django.urls import path
from category import views

app_name = 'category'
urlpatterns = [
    path('', views.IndexView, name='index'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.IndexView, name='index')
]

music/urls.py
from django.urls import path
from music import views

app_name = 'music'
urlpatterns = [
    path('', views.IndexView, name='index'),
    path('load-more', views.LoadMoreAPI, name='load-more'),
]

music/models.py
from django.db import models
from datetime import timedelta

# Create your models here.
class Music(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/')
    file = models.FileField(upload_to='musics/')
    duration = models.DurationField()
    publish_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Music'
        verbose_name_plural = 'Musics'

album/views.py
from django.shortcuts import render

# Create your views here.
def IndexView(request):
    return render(request,'album/index.html')

category/views.py
from django.shortcuts import render

# Create your views here.
def IndexView(request):
    return render(request,'category/index.html')

main/views.py
from django.shortcuts import render

# Create your views here.
def IndexView(request):
    return render(request, 'main/index.html')

music/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import JsonResponse
from music import models

# Create your views here.
def IndexView(request):
    musics = models.Music.objects.all()
    return render(request, 'music/index.html', {'musics': musics})

def LoadMoreAPI(request):
    musics = models.Music.objects.all()
    html_code = render_to_string('music/load-more.html', {'musics': musics})
    return JsonResponse({'html': html_code})

templates/category/index.html
{% extends 'shared/base.html' %}
{% load static %}

{% block title %}دسته‌بندی{% endblock title %}

{% block content %}
  <main id="page_content">
    <div
      class="hero"
      style="background-image: url({% static 'images/banner/home.jpg' %})"
    ></div>
    <div class="under-hero container">
      <div class="section">
        <div class="section__head">
          <h3 class="mb-0">
            ژانر های <span class="text-primary">موزیک</span>
          </h3>
        </div>
        <div class="row g-4">
          <div class="col-xl-3 col-sm-6">
            <div class="cover cover--round">
              <a href="genre-details.html" class="cover__image"
                ><img
                  src= "{% static 'images/background/horizontal/1.jpg' %}"
                  alt="Remix"
                />
                <div class="cover__image__content">
                  <span class="cover__title mb-1 fs-6 text-truncate"
                    >رمیکس</span
                  >
                </div></a
              >
            </div>
          </div>
          <div class="col-xl-3 col-sm-6">
            <div class="cover cover--round">
              <a href="genre-details.html" class="cover__image"
                ><img src= "{% static 'images/background/horizontal/2.jpg' %}" alt="Rock" />
                <div class="cover__image__content">
                  <span class="cover__title mb-1 fs-6 text-truncate"
                    >راک</span
                  >
                </div></a
              >
            </div>
          </div>
          <div class="col-xl-3 col-sm-6">
            <div class="cover cover--round">
              <a href="genre-details.html" class="cover__image"
                ><img src= "{% static 'images/background/horizontal/3.jpg' %}" alt="Sufi" />
                <div class="cover__image__content">
                  <span class="cover__title mb-1 fs-6 text-truncate"
                    >پاپ</span
                  >
                </div></a
              >
            </div>
          </div>
          <div class="col-xl-3 col-sm-6">
            <div class="cover cover--round">
              <a href="genre-details.html" class="cover__image"
                ><img
                  src= "{% static 'images/background/horizontal/4.jpg' %}"
                  alt="Romantic"
                />
                <div class="cover__image__content">
                  <span class="cover__title mb-1 fs-6 text-truncate"
                    >عاشقانه</span
                  >
                </div></a
              >
            </div>
          </div>
          <div class="col-xl-3 col-sm-6">
            <div class="cover cover--round">
              <a href="genre-details.html" class="cover__image"
                ><img
                  src= "{% static 'images/background/horizontal/5.jpg' %}"
                  alt="Sports"
                />
                <div class="cover__image__content">
                  <span class="cover__title mb-1 fs-6 text-truncate"
                    >جاز</span
                  >
                </div></a
              >
            </div>
          </div>
          <div class="col-xl-3 col-sm-6">
            <div class="cover cover--round">
              <a href="genre-details.html" class="cover__image"
                ><img
                  src= "{% static 'images/background/horizontal/6.jpg' %}"
                  alt="Retro"
                />
                <div class="cover__image__content">
                  <span class="cover__title mb-1 fs-6 text-truncate"
                    >نوستالژی</span
                  >
                </div></a
              >
            </div>
          </div>
        </div>
      </div>
      <div class="section">
        <div class="section__head">
          <h3 class="mb-0">
            ژانر های <span class="text-primary">پادکست</span>
          </h3>
        </div>
        <div class="row g-4">
          <div class="col-xl-3 col-sm-6">
            <div class="cover cover--round">
              <a href="genre-details.html" class="cover__image"
                ><img
                  src= "{% static 'images/background/horizontal/3.jpg' %}"
                  alt="Stories"
                />
                <div class="cover__image__content">
                  <span class="cover__title mb-1 fs-6 text-truncate"
                    >داستان</span
                  >
                </div></a
              >
            </div>
          </div>
          <div class="col-xl-3 col-sm-6">
            <div class="cover cover--round">
              <a href="genre-details.html" class="cover__image"
                ><img
                  src= "{% static 'images/background/horizontal/5.jpg' %}"
                  alt="Meditation & Workout"
                />
                <div class="cover__image__content">
                  <span class="cover__title mb-1 fs-6 text-truncate"
                    >ورزشی</span
                  >
                </div></a
              >
            </div>
          </div>
          <div class="col-xl-3 col-sm-6">
            <div class="cover cover--round">
              <a href="genre-details.html" class="cover__image"
                ><img
                  src= "{% static 'images/background/horizontal/6.jpg' %}"
                  alt="Business"
                />
                <div class="cover__image__content">
                  <span class="cover__title mb-1 fs-6 text-truncate"
                    >تجارت</span
                  >
                </div></a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer id="footer">
    </footer>
  </main>
{% endblock content %}

templates/music/index.html
{% extends 'shared/base.html' %}
{% load static %}

{% block title %}همه اهنگ‌ها{% endblock title %}

{% block content %}
  <main id="page_content">
    <div
      class="hero"
      style="background-image: url({% static 'images/banner/song.jpg' %})"
    ></div>
    <div class="under-hero container">
      <div class="section">
        <div class="section__head">
          <div class="flex-grow-1">
            <span class="section__subtitle"> ویژه‌ترین را گوش دهید</span>
            <h3 class="mb-0">
              ویژه <span class="text-primary">ترین ها</span>
            </h3>
          </div>
        </div>
        <div class="swiper-carousel swiper-carousel-button">
          <div dir="rtl"
            class="swiper"
            data-swiper-slides="5"
            data-swiper-autoplay="true"
          >
            <div class="swiper-wrapper">
              {% for music in musics %}
                <div class="swiper-slide">
                  <div
                    class="cover cover--round"
                    data-song-id="{{music.id}}"
                    data-song-name="{{music.name}}"
                    data-song-artist="ناشناس"
                    data-song-album="بدون آلبوم"
                    data-song-url="{{music.file.url}}"
                    data-song-cover="{{music.image.url}}"
                  >
                    <div class="cover__head">
                      <ul class="cover__label d-flex">
                        <li>
                          <span class="badge rounded-pill bg-danger"
                            ><i class="bi bi-heart-fill"></i
                          ></span>
                        </li>
                      </ul>
                      <div
                        class="cover__options dropstart d-inline-flex ms-auto"
                      >
                        <a
                          class="dropdown-link"
                          href="javascript:void(0);"
                          role="button"
                          data-bs-toggle="dropdown"
                          aria-label="Cover options"
                          aria-expanded="false"
                          ><i class="bi bi-three-dots-vertical fa-xl"></i
                        ></a>
                        <ul class="dropdown-menu dropdown-menu-sm">
                          <li>
                            <a
                              class="dropdown-item"
                              href="javascript:void(0);"
                              role="button"
                              data-favorite-id="1"
                              >مورد علاقه</a
                            >
                          </li>
                          <li>
                            <a
                              class="dropdown-item"
                              href="javascript:void(0);"
                              role="button"
                              data-playlist-id="1"
                              >افزودن به لیست</a
                            >
                          </li>
                          <li>
                            <a
                              class="dropdown-item"
                              href="javascript:void(0);"
                              role="button"
                              data-queue-id="1"
                              >افزودن به صف</a
                            >
                          </li>
                          <li>
                            <a
                              class="dropdown-item"
                              href="javascript:void(0);"
                              role="button"
                              data-next-id="1"
                              >بعدی برای پخش</a
                            >
                          </li>
                          <li>
                            <a
                              class="dropdown-item"
                              href="javascript:void(0);"
                              role="button"
                              >اشتراک</a
                            >
                          </li>
                          <li class="dropdown-divider"></li>
                          <li>
                            <a
                              class="dropdown-item"
                              href="javascript:void(0);"
                              role="button"
                              data-play-id="1"
                              >پخش</a
                            >
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="cover__image">
                      <img
                        src="{{music.image.url}}"
                        alt="{{music.name}}"
                      />
                      <button
                        type="button"
                        class="btn btn-play btn-default btn-icon rounded-pill"
                        data-play-id="1"
                      >
                        <i class="bi bi-play-fill fa-xl icon-play"></i>
                        <i class="bi bi-pause-fill fa-xl icon-pause"></i>
                      </button>
                    </div>
                    <div class="cover__foot">
                      <a
                        href="song-details.html"
                        class="cover__title text-truncate"
                        >{{music.name}}</a
                      >
                      <p class="cover__subtitle text-truncate">
                        <a href="artist-details.html">ناشناس</a>
                      </p>
                    </div>
                  </div>
                </div>             
              {% endfor %}
            </div>
          </div>
          <div class="swiper-button-prev btn-default rounded-pill"></div>
          <div class="swiper-button-next btn-default rounded-pill"></div>
        </div>
      </div>
      <div class="section">
        <div class="section__head align-items-center">
          <span class="d-block pe-3 fs-6 fw-semi-bold"
            >{{musics.count}} موزیک در لیست</span
          >
          <div>
            <select class="form-select" aria-label="Filter song">
              <option value="Popular">محبوب</option>
              <option value="Most played">بیشترین پخش</option>
              <option value="A to Z">الفبا (صعودی)</option>
              <option value="Z to A">الفبا (نزولی)</option>
            </select>
          </div>
        </div>
        <div class="list">
          <div id="music-list-container" class="row">
            {% for music in musics %}
              <div class="col-xl-6">
                <div
                  class="list__item"
                  data-song-id="{{music.id}}"
                  data-song-name="{{music.name}}"
                  data-song-artist="ناشناس"
                  data-song-album="بدون آلبوم"
                  data-song-url="{{music.file.url}}"
                  data-song-cover="{{music.image.url}}"
                >
                  <div class="list__cover">
                    <img
                      src="{{music.image.url}}"
                      alt="{{music.name}}"
                    />
                    <a
                      href="javascript:void(0);"
                      class="btn btn-play btn-sm btn-default btn-icon rounded-pill"
                      data-play-id="{{music.id}}"
                      aria-label="Play pause"
                      ><i class="bi bi-play-fill fa-xl icon-play"></i>
                      <i class="bi bi-pause-fill fa-xl icon-pause"></i
                    ></a>
                  </div>
                  <div class="list__content">
                    <a
                      href="song-details.html"
                      class="list__title text-truncate"
                      >{{music.name}}</a
                    >
                    <p class="list__subtitle text-truncate">
                      <a href="artist-details.html">ناشناس</a>
                    </p>
                  </div>
                  <ul class="list__option">
                    <li>
                      <a
                        href="javascript:void(0);"
                        role="button"
                        class="d-inline-flex"
                        aria-label="Favorite"
                        data-favorite-id="1"
                        ><i class="bi bi-heart fa-xl heart-empty"></i>
                        <i class="bi bi-heart-fill fa-xl heart-fill"></i
                      ></a>
                    </li>
                    <li>{{music.duration}}</li>
                    <li class="dropstart d-inline-flex">
                      <a
                        class="dropdown-link"
                        href="javascript:void(0);"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-label="Cover options"
                        aria-expanded="false"
                        ><i class="bi bi-three-dots fa-xl"></i
                      ></a>
                      <ul class="dropdown-menu dropdown-menu-sm">
                        <li>
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            role="button"
                            data-playlist-id="1"
                            >افزودن به لیست</a
                          >
                        </li>
                        <li>
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            role="button"
                            data-queue-id="1"
                            >افزودن به صف</a
                          >
                        </li>
                        <li>
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            role="button"
                            data-next-id="1"
                            >بعدی برای پخش</a
                          >
                        </li>
                        <li>
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            role="button"
                            >اشتراک</a
                          >
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            role="button"
                            data-play-id="1"
                            >پخش</a
                          >
                        </li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="mt-5 text-center">
          <button  id="load-more-music" class="btn btn-primary"
            ><div class="btn__wrap">
              <i id='load-more-arrow-icon' class="bi bi-arrow-clockwise fa-xl"></i> <span>بارگیری بیشتر</span>
            </div></button>
        </div>
      </div>
    </div>
    <footer id="footer">
    </footer>
  </main>
{% endblock content %}

templates/music/load-more.html
{% load static %}
  {% for music in musics %}
  <div class="col-xl-6">
    <div
      class="list__item"
      data-song-id="{{music.id}}"
      data-song-name="{{music.name}}"
      data-song-artist="ناشناس"
      data-song-album="بدون آلبوم"
      data-song-url="{{music.file.url}}"
      data-song-cover="{{music.image.url}}"
    >
      <div class="list__cover">
        <img
          src="{{music.image.url}}"
          alt="{{music.name}}"
        />
        <a
          href="javascript:void(0);"
          class="btn btn-play btn-sm btn-default btn-icon rounded-pill"
          data-play-id="{{music.id}}"
          aria-label="Play pause"
          ><i class="bi bi-play-fill fa-xl icon-play"></i>
          <i class="bi bi-pause-fill fa-xl icon-pause"></i
        ></a>
      </div>
      <div class="list__content">
        <a
          href="song-details.html"
          class="list__title text-truncate"
          >{{music.name}}</a
        >
        <p class="list__subtitle text-truncate">
          <a href="artist-details.html">ناشناس</a>
        </p>
      </div>
      <ul class="list__option">
        <li>
          <a
            href="javascript:void(0);"
            role="button"
            class="d-inline-flex"
            aria-label="Favorite"
            data-favorite-id="1"
            ><i class="bi bi-heart fa-xl heart-empty"></i>
            <i class="bi bi-heart-fill fa-xl heart-fill"></i
          ></a>
        </li>
        <li>{{music.duration}}</li>
        <li class="dropstart d-inline-flex">
          <a
            class="dropdown-link"
            href="javascript:void(0);"
            role="button"
            data-bs-toggle="dropdown"
            aria-label="Cover options"
            aria-expanded="false"
            ><i class="bi bi-three-dots fa-xl"></i
          ></a>
          <ul class="dropdown-menu dropdown-menu-sm">
            <li>
              <a
                class="dropdown-item"
                href="javascript:void(0);"
                role="button"
                data-playlist-id="1"
                >افزودن به لیست</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="javascript:void(0);"
                role="button"
                data-queue-id="1"
                >افزودن به صف</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="javascript:void(0);"
                role="button"
                data-next-id="1"
                >بعدی برای پخش</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="javascript:void(0);"
                role="button"
                >اشتراک</a
              >
            </li>
            <li class="dropdown-divider"></li>
            <li>
              <a
                class="dropdown-item"
                href="javascript:void(0);"
                role="button"
                data-play-id="1"
                >پخش</a
              >
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  {% endfor %}

  

templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>{% block title %}بصیر مدیا{% endblock title %}</title>
    <link href="{% static 'images/logos/favicon.png' %}" rel="icon" />
    <link rel="apple-touch-icon" href="{% static 'images/logos/touch-icon-iphone.png' %}" />
    <link
      rel="apple-touch-icon"
      sizes="152x152"
      href="{% static 'images/logos/touch-icon-ipad.png' %}"
    />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'images/logos/touch-icon-iphone-retina.png' %}"
    />
    <link
      rel="apple-touch-icon"
      sizes="167x167"
      href="{% static 'images/logos/touch-icon-ipad-retina.png' %}"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="{% static 'css/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/styles.bundle.css' %}" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="line_loader"></div>
    <div id="loader">
      <div class="loader">
        <div class="loader__eq mx-auto">
          <span></span> <span></span> <span></span> <span></span> <span></span>
          <span></span>
        </div>
        <span class="loader__text mt-2">در حال بارگیری . . .</span>
      </div>
    </div>
    <div id="wrapper">
      {% block header %}{% include 'shared/header.html' %}{% endblock header %}
      {% block sidebar %}{% include 'shared/sidebar.html' %}{% endblock sidebar %}
      {% block content %}{% endblock content %}
    </div>
    {% block player %}{% include 'shared/player.html' %}{% endblock player %}
    <script src="https://kit.fontawesome.com/3506de607c.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/plugins.bundle.js' %}"></script>
    <script src="{% static 'js/scripts.bundle.js' %}"></script>
  </body>
</html>

templates/shared/sidebar.html
{% load static %}
{% url 'main:index' as main_index_url %}
{% url 'music:index' as music_index_url %}
{% url 'category:index' as category_index_url %}
{% url 'album:index' as album_index_url %}
  <aside id="sidebar">
    <div
      class="sidebar-head d-flex align-items-center justify-content-between"
    >
      <a href="/listen-music/" class="brand external"
        ><img src="{% static 'images/logos/logo.svg' %}" alt="Listen app" /> </a
      ><a
        href="javascript:void(0);"
        role="button"
        class="sidebar-toggler"
        aria-label="Sidebar toggler"
        ><div class="d-none d-lg-block">
          <i class="bi bi-list fa-2xl sidebar-menu-1"></i>
          <i class="bi bi-list fa-2xl sidebar-menu-2"></i>
        </div>
        <i class="bi bi-list fa-2xl d-lg-none"></i
      ></a>
    </div>
    <div class="sidebar-body" data-scroll="true">
      <nav class="navbar d-block p-0">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{{main_index_url}}" class="nav-link d-flex align-items-center  {% if request.path == main_index_url %}active{% endif %}"
              ><i class="bi bi-house fa-xl"></i>
              <span class="ps-3">خانه</span></a
            >
          </li>

          <li class="nav-item">
            <a href="{{music_index_url}}" class="nav-link d-flex align-items-center {% if request.path == music_index_url %}active{% endif %}"
              ><i class="bi bi-music-note fa-xl"></i>
              <span class="ps-3">موزیک</span></a
            >
          </li>

          <li class="nav-item">
            <a href="{{category_index_url}}" class="nav-link d-flex align-items-center {% if request.path == category_index_url %}active{% endif %}"
              ><i class="bi bi-list-ul fa-xl"></i>
              <span class="ps-3">ژانر</span></a
            >
          </li>

          <li class="nav-item">
            <a href="{{album_index_url}}" class="nav-link d-flex align-items-center {% if request.path == album_index_url %}active{% endif %}"
              ><i class="bi bi-mic-fill fa-xl"></i>
              <span class="ps-3">آلبوم</span></a
            >
          </li>
          <li class="nav-item">
            <a
              href="artists.html"
              class="nav-link d-flex align-items-center"
              ><i class="bi bi-person-badge fa-xl"></i>
              <span class="ps-3">هنرمندان</span></a
            >
          </li>
          <li class="nav-item">
            <a
              href="stations.html"
              class="nav-link d-flex align-items-center"
              ><i class="bi bi-play-btn-fill fa-xl"></i>
              <span class="ps-3">موزیک ویدئو</span></a
            >
          </li>
        </ul>
      </nav>
    </div>
    <div class="sidebar-foot">
      <a href="add-music.html" class="btn btn-primary d-flex"
        ><div class="btn__wrap">
          <i class="bi bi-music-note-beamed fa-xl"></i> <span> &nbsp افزودن موزیک</span>
        </div></a
      >
    </div>
  </aside>